routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('mainhome');

Route::get('/testing', 'HomeController@test')->name('test')->middleware('test');
Route::post('/feedback', 'HomeController@feedback')->name('feedback');
Route::get('/online', 'HomeController@online')->name('online');


Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::get('church', 'PageController@church')->name('pages.church');
Route::get('pastor', 'PageController@pastor')->name('pages.pastor');
Route::get('schedule_contact', 'PageController@contacts')->name('pages.contacts');

Route::get('categories', 'CategoryController@index')->name('category.index')->middleware('test'); // на вермя разработки повесил middleware
Route::get('category/{slug}', 'PostController@postByCategory')->name('category.posts')->middleware('test'); // на вермя разработки повесил middleware

Route::get('tag/{slug}', 'PostController@postByTag')->name('tag.posts')->middleware('test'); // на вермя разработки повесил middleware

Route::get('posts', 'PostController@index')->name('post.index')->middleware('test'); // на вермя разработки повесил middleware
Route::get('post/{slug}', 'PostController@details')->name('post.details')->middleware('test'); // на вермя разработки повесил middleware

Route::get('search', 'SearchController@search')->name('search');

Route::get('/profile/{username}', 'AuthorController@profile')->name('author.profile');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');

    Route::post('comment/{post}', 'CommentController@store')->name('comment.store');

    // Route::get('search', 'SearchController@search')->name('search');
});

Route::group(
    ['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']],
    function () {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
        Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

        Route::resource('tag', 'TagController');
        Route::resource('category', 'CategoryController');
        Route::resource('post', 'PostController');
        Route::resource('bible', 'BibleController');

        Route::get('pending/post', 'PostController@pending')->name('post.pending');
        Route::put('post/{post}/approve', 'PostController@approval')->name('post.approve');

        Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

        Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
        Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');

        Route::get('/author', 'AuthorController@index')->name('author.index');
        Route::delete('/author/{author}', 'AuthorController@destroy')->name('author.destroy');

        Route::get('/comments', 'CommentController@index')->name('comments.index');
        Route::delete('/comments/{comment}', 'CommentController@destroy')->name('comments.destroy');
    }
);

Route::group(
    ['as' => 'author.', 'prefix' => 'author', 'namespace' => 'Author', 'middleware' => ['auth', 'author']],
    function () {
        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
        Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

        Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::resource('post', 'PostController');

        Route::get('/comments', 'CommentController@index')->name('comments.index');
        Route::delete('/comments/{comment}', 'CommentController@destroy')->name('comments.destroy');
    }
);

resources/views/admin/authors.blade.php
@extends('layouts.backend.app')

@section('title', 'All Authors')

@push('css')
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="container-fluid">

    @if (session('successMsg'))
        <div class="alert alert-success m-t-15" role="alert">
          {{ session('successMsg') }}  
    @endif

    </div>
    <!-- Basic Examples -->

    <!-- #END# Basic Examples -->
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                       Все авторы
                        <span class="badge bg-green">{{ $authors->count() }}</span>
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Имя</th>
                                    <th>Постов</th>
                                    <th>Комментариев</th>
                                    <th>Лайков</th>
                                    <th>Создан</th>
                                    <th>Действия</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>№</th>
                                    <th>Имя</th>
                                    <th>Постов</th>
                                    <th>Комментариев</th>
                                    <th>Лайков</th>
                                    <th>Создан</th>
                                    <th>Действия</th>
                                </tr>
                            </tfoot>

                            <tbody>
                                @foreach ($authors as $key => $author)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $author->name }}</td>
                                        <td><span class="badge bg-green">{{ $author->posts_count }}</span></td>
                                        <td><span class="badge bg-green">{{ $author->favorite_posts_count }}</span></td>
                                        <td><span class="badge bg-green">{{ $author->comments_count }}</span></td>
                                        <td>{{ $author->created_at }}</td>
                                        <td class="text-center">
                                            {{-- Надо сделать редактирование юзеров --}}
                                        {{-- <a href="" class="btn btn-info waves-effect">
                                            <i class="material-icons">edit</i>
                                        </a> --}}
                                        <button class="btn btn-danger waves-effect" onclick="deleteAuthor({{ $author->id }})">
                                            <i class="material-icons">delete</i>
                                        </button>

                                    <form id="delete-form-{{ $author->id }}" action="{{ route('admin.author.destroy', $author) }}" method="POST" style="display:none;">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->
</div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>

    <!-- Custom Js -->
    <script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        function deleteAuthor(id)
        {
            const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success m-l-15',
                cancelButton: 'btn btn-danger'
            },
            buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
            }).then((result) => {
            if (result.value) {
                event.preventDefault();
                document.getElementById('delete-form-' + id).submit();
            } else if (
                /* Read more about handling dismissals below */
                result.dismiss === Swal.DismissReason.cancel
            ) {
                swalWithBootstrapButtons.fire(
                'Cancelled',
                'Your imaginary file is safe :)',
                'error'
                )
            }
            })
        }
    </script>
@endpush

resources/views/admin/favorite.blade.php
@extends('layouts.backend.app')

@section('title', 'Favorite Post')

@push('css')
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="container-fluid">
    <div class="block-header">

    @if (session('successMsg'))
        <div class="alert alert-success m-t-15" role="alert">
          {{ session('successMsg') }}  
        </div> 
    @endif

    </div>
    <!-- Basic Examples -->

    <!-- #END# Basic Examples -->
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Посты с лайками
                        <span class="badge bg-green">{{ $posts->count() }}</span>
                    </h2>
                
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Заголовок</th>
                                    <th>Автор</th>
                                    <th><i class="material-icons">favorite</i></th>
                                    <th><i class="material-icons">comment</i></th>
                                    <th><i class="material-icons">visibility</i></th>
                                    <th>Действия</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>№</th>
                                    <th>Заголовок</th>
                                    <th>Автор</th>
                                    <th><i class="material-icons">favorite</i></th>
                                    <th><i class="material-icons">comment</i></th>
                                    <th><i class="material-icons">visibility</i></th>
                                    <th>Действия</th>
                                </tr>
                            </tfoot>

                            <tbody>
                                @foreach ($posts as $key => $post)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ str_limit($post->title, 15) }}</td>
                                        <td>{{ $post->user->name }}</td>
                                        <td>{{ $post->favorite_to_users->count() }}</td>
                                        <td>{{ $post->comments->count() }}</td>
                                        <td>{{ $post->view_count }}</td>
                                       
                                     
                                        <td class="text-center">
                                        <a href="{{ route('admin.post.show', $post) }}" class="btn btn-info waves-effect" title="show">
                                            <i class="material-icons">visibility</i>
                                        </a>
                                        <button class="btn btn-danger waves-effect" onclick="removePost({{ $post->id }})" title="delete">
                                            <i class="material-icons">delete</i>
                                        </button>
                                    <form id="remove-form-{{ $post->id }}" action="{{ route('post.favorite', $post) }}" method="POST" style="display:none;">
                                        @csrf
                                    </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->
</div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>


    <!-- Custom Js -->
    <script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        function removePost(id)
        {
            const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success m-l-15',
                cancelButton: 'btn btn-danger'
            },
            buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
            }).then((result) => {
            if (result.value) {
                event.preventDefault();
                document.getElementById('remove-form-' + id).submit();
            } else if (
                /* Read more about handling dismissals below */
                result.dismiss === Swal.DismissReason.cancel
            ) {
                swalWithBootstrapButtons.fire(
                'Cancelled',
                'Your imaginary file is safe :)',
                'error'
                )
            }
            })
        }

    </script>
@endpush

resources/views/admin/settings.blade.php
@extends('layouts.backend.app')

@section('title', 'Admin settings')

@push('css')
  
@endpush

@section('content')
<div class="container-fluid">
    <div class="row clearfix">
        @if (session('successMsg'))
            <div class="alert alert-success m-t-15" role="alert">
            {{ session('successMsg') }}  
            </div> 
        @endif
        @if (session('logginErrorMsg'))
            <div class="alert alert-danger m-t-15" role="alert">
            {{ session('logginErrorMsg') }}  
            </div> 
        @endif
        @if ($errors->any())
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger m-t-15" role="alert">
                    {{ $error }}  
                </div> 
            @endforeach
        @endif
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Настройки
                    </h2>
                </div>
                <div class="body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs tab-nav-right" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#home_only_icon_title" data-toggle="tab">
                                <i class="material-icons">face</i> Обновить профиль
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#profile_only_icon_title" data-toggle="tab">
                                <i class="material-icons">change_history</i> Изменить пароль
                            </a>
                        </li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="home_only_icon_title">
                            <div class="row clearfix">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="header">

                                        </div>
                                        <div class="body">
                                        <form action="{{ route('admin.profile.update') }}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')   
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="name">Имя</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <input type="text" id="name" class="form-control" placeholder="Enter your name" name="name" value="{{ Auth::user()->name }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="email">Email</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <input type="text" id="email" class="form-control" placeholder="Enter your email" name="email" value="{{ Auth::user()->email }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="image">Картинка</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <input type="file" name="image">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="about">Описание</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <textarea name="about" id="about" style="width:100%; height:150px;">{{ Auth::user()->about }}</textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                                <div class="row clearfix">
                                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Обновить</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="profile_only_icon_title">
                            <form action="{{ route('admin.password.update') }}" method="POST" class="form-horizontal">
                                @csrf
                                @method('PUT')   
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="old_password">Старый пароль</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                            <input type="password" id="old_password" class="form-control" placeholder="Enter your old password" name="old_password">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="password">Новый пароль</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                            <input type="password" id="password" class="form-control" placeholder="Enter your new password" name="password">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="confirm_password">Подтвердить</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                            <input type="password" id="confirm_password" class="form-control" placeholder="Confirm your password" name="password_confirmation">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">update</button>
                                        </div>
                                    </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')

@endpush