routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('mainhome');

Route::get('/testing', 'HomeController@test')->name('test')->middleware('test');
Route::post('/feedback', 'HomeController@feedback')->name('feedback');
Route::get('/online', 'HomeController@online')->name('online');


Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::get('church', 'PageController@church')->name('pages.church');
Route::get('pastor', 'PageController@pastor')->name('pages.pastor');
Route::get('schedule_contact', 'PageController@contacts')->name('pages.contacts');

Route::get('categories', 'CategoryController@index')->name('category.index')->middleware('test'); // на вермя разработки повесил middleware
Route::get('category/{slug}', 'PostController@postByCategory')->name('category.posts')->middleware('test'); // на вермя разработки повесил middleware

Route::get('tag/{slug}', 'PostController@postByTag')->name('tag.posts')->middleware('test'); // на вермя разработки повесил middleware

Route::get('posts', 'PostController@index')->name('post.index')->middleware('test'); // на вермя разработки повесил middleware
Route::get('post/{slug}', 'PostController@details')->name('post.details')->middleware('test'); // на вермя разработки повесил middleware

Route::get('search', 'SearchController@search')->name('search');

Route::get('/profile/{username}', 'AuthorController@profile')->name('author.profile');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');

    Route::post('comment/{post}', 'CommentController@store')->name('comment.store');

    // Route::get('search', 'SearchController@search')->name('search');
});

Route::group(
    ['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']],
    function () {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
        Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

        Route::resource('tag', 'TagController');
        Route::resource('category', 'CategoryController');
        Route::resource('post', 'PostController');
        Route::resource('bible', 'BibleController');

        Route::get('pending/post', 'PostController@pending')->name('post.pending');
        Route::put('post/{post}/approve', 'PostController@approval')->name('post.approve');

        Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

        Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
        Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');

        Route::get('/author', 'AuthorController@index')->name('author.index');
        Route::delete('/author/{author}', 'AuthorController@destroy')->name('author.destroy');

        Route::get('/comments', 'CommentController@index')->name('comments.index');
        Route::delete('/comments/{comment}', 'CommentController@destroy')->name('comments.destroy');
    }
);

Route::group(
    ['as' => 'author.', 'prefix' => 'author', 'namespace' => 'Author', 'middleware' => ['auth', 'author']],
    function () {
        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
        Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

        Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::resource('post', 'PostController');

        Route::get('/comments', 'CommentController@index')->name('comments.index');
        Route::delete('/comments/{comment}', 'CommentController@destroy')->name('comments.destroy');
    }
);

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;

class AuthorController extends Controller
{
    public function index()
    {
        $authors = User::author()
            ->withCount('posts')
            ->withCount('favorite_posts')
            ->withCount('comments')
            ->get();
        // return dd($authors);
        return view('admin.authors', compact('authors'));;
    }

    public function destroy(User $author)
    {
        $user = User::findOrFail($author->id);
        if ($user) {
            $user->delete();
        }

        return redirect(route('admin.author.index'))->with('successMsg', 'User deleted!!!');
    }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Comment;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $comments = $user->comments()->latest()->get();
        return view('author.comments.index', compact('comments'));
    }

    public function destroy(Comment $comment)
    {
        $commentDelete = Comment::findOrFail($comment->id);
        if ($commentDelete) {
            $commentDelete->delete();
        }

        return redirect(route('admin.comments.index'))->with('successMsg', 'Comment deleted!!!');
    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;

class DashboardController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $posts = $user->posts;
        $popular_posts = $user->posts()
            ->withCount('comments')
            ->withCount('favorite_to_users')
            ->orderBy('view_count', 'desc')
            ->orderBy('comments_count')
            ->orderBy('favorite_to_users_count')->take(5)->get();
        $total_pending_posts = $posts->where('is_approved', false)->count();
        $all_views = $posts->sum('view_count');
        return view('author.dashboard', compact('posts', 'popular_posts', 'total_pending_posts', 'all_views'));
    }
}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FavoriteController extends Controller
{
    public function index()
    {
        $posts = Auth::user()->favorite_posts;
        return view('author.favorite', compact('posts'));
    }
}

app/Http/Controllers/Author/PostController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Tag;
use App\Category;
use Carbon\Carbon;
use App\User;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use App\Notifications\NewAuthorPost;
use Illuminate\Support\Facades\Notification;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Auth::User()->posts()->latest()->get();
        return view('author.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('author.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|min:3|unique:posts',
            'image' => 'mimes:jpg,png,jpeg',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required',
        ]);

        $image = $request->file('image');
        $slug = str_slug($request->title);

        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . uniqid() . '.' . $image->getClientOriginalExtension();

            // check post dir is exists
            $this->dirExists('post');

            $postImage = Image::make($image)->resize(1600, 1066)->stream();
            Storage::disk('public')->put('post/' . $imageName, $postImage);
        } else {
            $imageName = 'default.png';
        }

        $post = new Post();
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->image = $imageName;
        $post->slug = $slug;
        $post->body = $request->body;
        $post->status = isset($request->status) ? true : false;
        $post->is_approved = false;
        $post->save();

        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);

        // оповещения на почту будут проблемы если, просто убрать этот блок
        // $users = User::where('role_id', 1)->get();
        // Notification::send($users, new NewAuthorPost($post));

        return redirect(route('author.post.index'))->with('successMsg', 'Post succesfull added!!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        if ($post->user_id != Auth::id()) {
            return redirect()->back();
        }
        return view('author.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        if ($post->user_id != Auth::id()) {
            return redirect()->back();
        }
        $categories = Category::all();
        $tags = Tag::all();
        return view('author.post.edit', compact('categories', 'tags', 'post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        if ($post->user_id != Auth::id()) {
            return redirect()->back();
        }
        $this->validate($request, [
            'title' => 'required|min:3',
            'image' => 'mimes:jpg,png,jpeg',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required',
        ]);

        $image = $request->file('image');
        $slug = str_slug($request->title);
        $status = isset($request->status) ? true : false;

        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . uniqid() . '.' . $image->getClientOriginalExtension();

            // check post dir is exists
            $this->dirExists('post');

            // delete category image
            $this->deleteImage('post/', $post->image);

            $postImage = Image::make($image)->resize(1600, 1066)->stream();
            Storage::disk('public')->put('post/' . $imageName, $postImage);
        } else {
            $imageName = $post->image;
        }

        $post->update([
            'title' => $request->title,
            'image' => $imageName,
            'slug' => $slug,
            'status' => $status,
            'body' => $request->body
        ]);

        // удаляем все теги и записываем по новой
        $post->categories()->sync(request('categories'));

        $post->tags()->sync(request('tags'));

        return redirect(route('author.post.index'))->with('successMsg', 'Post updated!!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if ($post->user_id != Auth::id()) {
            return redirect()->back();
        }
        $post = Post::findOrFail($post->id);
        if ($post) {
            $post->categories()->detach();
            $post->tags()->detach();
            $post->delete();

            // delete post image
            $this->deleteImage('post/', $post->image);
        }

        return redirect(route('author.post.index'))->with('successMsg', 'Post was deleted!!!');
    }

    public function dirExists($dir)
    {
        if (!Storage::disk('public')->exists($dir)) {
            Storage::disk('public')->makeDirectory($dir);
        }
    }

    public function deleteImage($dir, $img)
    {
        if (Storage::disk('public')->exists($dir . $img)) {
            Storage::disk('public')->delete($dir . $img);
        }
    }

    public function checkUserId(Post $post)
    {
        if ($post->user_id != Auth::id()) {
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Author/SettingsController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Hash;
use App\User;

class SettingsController extends Controller
{
    public function index()
    {
        return view('author.settings');
    }

    public function updateProfile(Request $request)
    {
        // return dd($request->all());
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
            'image' => 'mimes:jpg,png,jpeg'
        ]);

        $image = $request->file('image');
        $slug = str_slug($request->name);
        $user = User::findOrFail(Auth::id());

        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . uniqid() . '.' . $image->getClientOriginalExtension();

            // create dir for profile image
            $this->dirExists('profile');

            // delete profile image
            $this->deleteImage('profile/', $user->image);

            // add profile image
            $userImage = Image::make($image)->resize(500, 500)->stream();
            Storage::disk('public')->put('profile/' . $imageName, $userImage);
        } else {
            $imageName = $user->image;
        }
        $user->update([
            'name' => $request->name,
            'email' => $request->email,
            'image' => $imageName,
            'about' => isset($request->about) ? $request->about : $user->about
        ]);

        return redirect()->back()->with('successMsg', 'Profile updated!!!');
    }

    public function updatePassword(Request $request)
    {
        // return dd($request->all());
        $this->validate($request, [
            'old_password' => 'required',
            'password' => 'required|confirmed'
        ]);

        $hashedPass = Auth::user()->password;
        if (Hash::check($request->old_password, $hashedPass) && !Hash::check($request->password, $hashedPass)) {
            $user = User::find(Auth::id());
            $user->password = Hash::make($request->password);
            $user->save();
            Auth::logout();
            return redirect()->back()->with('successMsg', 'Good!');
        }

        return redirect()->back()->with('logginErrorMsg', 'Somfing wrong, try again!');
    }

    public function dirExists($dir)
    {
        if (!Storage::disk('public')->exists($dir)) {
            Storage::disk('public')->makeDirectory($dir);
        }
    }

    public function deleteImage($dir, $img)
    {
        if (Storage::disk('public')->exists($dir . $img)) {
            Storage::disk('public')->delete($dir . $img);
        }
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class AuthorController extends Controller
{
    public function profile($username)
    {
        $user = User::where('username', $username)->first();
        $posts = $user->posts()->approved()->published()->paginate(4);
        return view('profile.author', compact('user', 'posts'));;
    }
}

resources/views/author/settings.blade.php
@extends('layouts.backend.app')

@section('title', 'Author settings')

@push('css')
  
@endpush

@section('content')
<div class="container-fluid">
    <div class="row clearfix">
        @if (session('successMsg'))
            <div class="alert alert-success m-t-15" role="alert">
            {{ session('successMsg') }}  
            </div> 
        @endif
        @if (session('logginErrorMsg'))
            <div class="alert alert-danger m-t-15" role="alert">
            {{ session('logginErrorMsg') }}  
            </div> 
        @endif
        @if ($errors->any())
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger m-t-15" role="alert">
                    {{ $error }}  
                </div> 
            @endforeach
        @endif
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Настройки
                    </h2>
                </div>
                <div class="body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs tab-nav-right" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#home_only_icon_title" data-toggle="tab">
                                <i class="material-icons">face</i> Обновить профиль
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#profile_only_icon_title" data-toggle="tab">
                                <i class="material-icons">change_history</i> Изменить пароль
                            </a>
                        </li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="home_only_icon_title">
                            <div class="row clearfix">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="header">

                                        </div>
                                        <div class="body">
                                        <form action="{{ route('author.profile.update') }}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')   
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="name">Имя</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <input type="text" id="name" class="form-control" placeholder="Enter your name" name="name" value="{{ Auth::user()->name }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="email">Email</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <input type="text" id="email" class="form-control" placeholder="Enter your email" name="email" value="{{ Auth::user()->email }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="image">Картинка</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <input type="file" name="image">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row clearfix">
                                                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                    <label for="about">Описание</label>
                                                </div>
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                    <div class="form-group">
                                                        <div class="form-line">
                                                        <textarea name="about" id="about" style="width:100%; height:150px;">{{ Auth::user()->about }}</textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                                <div class="row clearfix">
                                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Обновить</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="profile_only_icon_title">
                            <form action="{{ route('author.password.update') }}" method="POST" class="form-horizontal">
                                @csrf
                                @method('PUT')   
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="old_password">Старый пароль</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                            <input type="password" id="old_password" class="form-control" placeholder="Enter your old password" name="old_password">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="password">Новый пароль</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                            <input type="password" id="password" class="form-control" placeholder="Enter your new password" name="password">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="confirm_password">Подтвердить</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                            <input type="password" id="confirm_password" class="form-control" placeholder="Confirm your password" name="password_confirmation">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Обновить</button>
                                        </div>
                                    </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')

@endpush